extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MSEObserver
        a_observer: EMAMSEObserver
        w_fakequantize: AdaRoundFakeQuantize
        a_fakequantize: QDropFakeQuantize
        w_qscheme:
            bit: 2
            symmetry: False
            per_channel: True
            pot_scale: False
            p: 2.4
        a_qscheme:
            bit: 4
            symmetry: False
            per_channel: False
            pot_scale: False
            p: 2.4
quantize:
    quantize_type: ptq # support ptq or qat
    cali_batchsize: 16
    reconstruction:
        pattern: block
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.1
        max_count: 20000
        b_range: [20,2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        prob: 0.5
model:                    # architecture details
    type: mobilenet_v2        # model name
    kwargs:
        num_classes: 1000
    path: /mnt/lustre/weixiuying/model_zoo/mobilenetv2.pth.tar
data:
    path: /mnt/lustre/share/ImageNet-Pytorch/
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005
